### PR TITLE
Add Initial Activity Streams 2.0 Example

### PR DESCRIPTION
**Pull request by jasnell**
Adds an initial Activity Streams 2.0 example along with a redirection for the 
development context document.

### CODE REVIEW

**Comment by msporny** [comment]
Thanks for the example! :)

Any chance that you might alias "@id" -> "id", and "@type" -> "type" in the AS2 JSON-LD Context in the future?

**Comment by msporny** [comment]
Also, any chance you could add the CORS headers to the AS2 JSON-LD Context? That "Use development XYZ" is a bit strange for something that you should have control over.

**Comment by jasnell** [comment]
The `http://www.w3.org/ns/activitystreams#` url to host the AS2 JSON-LD context document has not yet been set up. I currently have the context document hosted at `http://asjsonld.mybluemix.net` and it does have the CORS headers set. Because the "official" url is not yet set up we need to have the redirect in there.

And it's not likely that we'll map "@id" to "id" and "@type" to "type". Any particular reason why on those?

**Comment by jasnell** [comment]
I'm working on it ;-) ... I can definitely change the example to point to the current dev context location and update it when the official one is finally set up.

**Comment by jasnell** [comment]
https://github.com/json-ld/json-ld.org/pull/381

**Comment by msporny** [comment]
> re: problem w/ the official URL

ETA on when this'll be fixed?

> not likely that we'll map "@id" to "id" and "@type" to "type". Any particular reason why on those?

Because it makes the data look more foreign than it needs to be to people that are used to JSON, but not used to JSON-LD. Specifically, it's nice to be able to use dot-notation in the languages that support it:
```javascript
if(obj.id === theOneImLookingFor) {
```
instead of this:

```javascript
if(obj['@id'] === theOneImLookingFor) {
```

The top one is easier to parse while looking through code.

**Comment by jasnell** [comment]
No ETA yet. I'll follow up with the W3C contact this next week.

**Comment by akuckartz** [comment]
@msporny That the "@" in front of "id" makes the data look more foreign than without is an interesting opinion. It _might_ be true though. I wonder what you would do if you could rewrite the JSON-LD spec.

My opinion is different: I think the "@" indicates that the data is machine readable in an additional sense.

**Comment by msporny** [comment]
@akuckartz if we could re-write the JSON-LD spec, we'd do the exact same thing. The reason we used '@'-prefixed keywords was so that we could guarantee that the JSON-LD syntax wouldn't conflict with 99.999% of JSON markup out there. If we had standardized on 'id' or 'type' it would've started a firestorm of "well, my data has 'id' and 'type' all over it and therefore I can't use JSON-LD at all, you guys suck, I'm going to write a scathing blog post about how out of touch JSON-LD is now and share it with all my friends!" :P (a bit hyperbolic, but you get the idea).

**Comment by akuckartz** [comment]
@msporny I get the idea, I already encountered significant amounts of Semaphobia ...

I will forward your suggestion to other communities. We will see how Hydra and schema.org react ;-)

**Comment by vanthome** [comment]
@msporny I don't understand why the reason to go for`@xxx` you have outlined no longer exists?! I JSON-LD isn't out there for too long and I don't see that existing JSON based data has changed that much ever since.

**Comment by lanthaler** [comment]
Hmm... if we would start from scratch again, then using id instead of @id might be an option.. but we can't. I thus think it is less confusing for users to simply stick to the standard and use those keywords. They will recognize them.. basically all blog posts, tutorials, presentations etc. that have been written use them. So should an upcoming W3C standard IMHO.

**Pull request merged**
