### PR TITLE
Framing update and modernization of json-ld and json-ld-api

### PR DESCRIPTION
**Pull request by gkellogg**
This PR principally serves as an update to json-ld-framing, based on algorithms actually implemented in many implementations. It is intended to serve as a basis for more updates to framing.

Notable (perhaps controversial) is a change to the style of describing the algorithm, which intends to be less of an exercise in detailing the steps to implement this than a set of normative requirements of an implementation; this has been a source of complaints about the 1.0 algorithms in general, and came up specifically in comments about updating the framing API (e.g., [this one](https://lists.w3.org/Archives/Public/public-linked-json/2016Aug/0022.html)).

The update also attempts to distinguish the JSON syntax from that of a more WebIDL generic implementation, for example using **dictionary** instead of **JSON object** when discussing processing steps. In general, trying to distinguish between abstract structures as part of an implementation and syntactic structures when talking about the form of a JSON-LD document.

As much has changed since the 1.0 specs, the docs have a comprehensive update for ReSpec, abandoning the local copy used in favor of the W3C maintained version. Also, WebIDL has changed to WebIDL 2, and our API implementation mechanism has been deprecated. I also made similar changes to json-ld and json-ld-api in advance of other changes the CG may make to those specs in the future.

Considering a general CG update to json-ld and json-ld-api, it probably also makes sense to roll the framing algorithm into json-ld-api, but that can wait for a future date.

To simplify review, rawgit links to the documents can be found at [json-ld](https://rawgit.com/json-ld/json-ld.org/framing-update/spec/latest/json-ld/index.html), [json-ld-api](https://rawgit.com/json-ld/json-ld.org/framing-update/spec/latest/json-ld-api/index.html), and [json-ld-framing](https://rawgit.com/json-ld/json-ld.org/framing-update/spec/latest/json-ld-framing/index.html).

### CODE REVIEW

**Comment by dlongley** [comment]
I think we should merge this.

**Comment by akuckartz** [comment]
I get 404 errors when I dereference the three rawgit URLs.

**Comment by gkellogg** [comment]
The rawgit links were based on the now-deleted framing-update branch. After the merge, these documents can be found at the normal place linked off of the website for the latest drafts:

* http://json-ld.org/spec/latest/json-ld/
* http://json-ld.org/spec/latest/json-ld-api/
* http://json-ld.org/spec/latest/json-ld-framing/

**Comment by akuckartz** [comment]
@gkellogg The first two URLs forward to the two W3C recommendations from 2014.

**Comment by gkellogg** [comment]
Looks like there are some redirects in place, which I'll look into. Thanks for the heads' up!

**Comment by gkellogg** [comment]
Should be fixed now.

**Comment by akuckartz** [comment]
@gkellogg Now it' s perfect!

**Pull request merged**
