### PR TITLE
Rename 'Github' to 'GitHub'

### PR DESCRIPTION
**Pull request by veyndan**
GitHub should be stylized with a capital "H".

Generated the PR by executed `find . -type f -exec sed -i '' "s/Github/GitHub/g" {} +` from the project root.

### CODE REVIEW

**Comment by davidlehn** [comment]
- I don't think any of the historical dated specs should be changed, regardless of the correction.  They are meant to be a snapshot in time.
- This adds an empty .ico file.

**Comment by veyndan** [comment]
@davidlehn Updated the PR with the proposed changes

**Review by gkellogg — APPROVED** [review]
Other than index.html, the other files obsolete. Best practices should probably reference the WG Note.

**Review by davidlehn — APPROVED** [review]

**Comment by veyndan** [comment]
> Other than index.html, the other files obsolete. Best practices should probably reference the WG Note.

@gkellogg How could I go about doing that? Would I just delete the non-`index.html` files here and replace the links with a reference to the WG note? What/where is the WG note?

**Comment by gkellogg** [comment]
In other cases, we've both updated .htaccess to forward, and added some HTML. For example see https://github.com/json-ld/json-ld.org/blob/main/spec/latest/.htaccess.
Also, the test suite has an HTML redirect:

https://github.com/json-ld/json-ld.org/blob/f4b8dc9bb04ea3983a8c49bbe69913f6ff118989/test-suite/index.html#L10

**Pull request merged**
