### PR TITLE
These IRI normalization tests directly correspond to those for

### LINKED ISSUE #394: Create IRI Resolution tests similar to those used for Turtle
See https://github.com/w3c/rdf-tests/issues/6

### PR DESCRIPTION
**Pull request by gkellogg**
https://github.com/w3c/rdf-tests/issues/6. Fixes #394.

### CODE REVIEW

**Comment by gkellogg** [comment]
@dlongley @lanthaler @ansell @sblom: You might check your implementations against these before we merge the PR. See https://github.com/w3c/rdf-tests/issues/6 for more detail, but the logic should be the same for all RDF serialization formats.

**Comment by RubenVerborgh** [comment]
We should perhaps not merge before the discussion on w3c/rdf-tests#6 has ended. Some of the tests are still up for debate (their correctness is not questioned, only whether all cases need to be included).

**Comment by gkellogg** [comment]
Makes sense. Still, it would be good to see where other implementations are.

**Comment by dlongley** [comment]
@gkellogg,

I haven't had a chance to take a look yet -- it's a very busy week. Will try to get to it when I can.

**Comment by ansell** [comment]
@gkellogg Hi, sorry, I have been at a conference so far this week and won't have a chance to look at this until next week at the earliest. I have been following the relative IRI discussions on the mailing lists, but have not yet tested them with JSONLD-Java or Sesame.

**Comment by lanthaler** [comment]
Sorry for the delay from my side as well. I’ve just tested the new test cases. My implementation passes all of them out of the box.

**Comment by lanthaler** [comment]
Sorry for the delay from my side as well. I’ve just tested the new test cases. My implementation passes all of them out of the box.

**Comment by gkellogg** [comment]
Great! Based on discussion on the Turtle side (see w3c/rdf-tests/issues/6 and w3c/rdf-tests/pull/13), we'll probably reduce the normative checks a bit further. I'll just wait for that to resolve.

**Pull request merged**
