### PR TITLE
Update main site license to use W3C Software and Document License.

### LINKED ISSUE #560: Document license -> w3c permissive software and document license?
If we switched the license officially to the [w3c permissive software and document license](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document) that may be a good idea, especially since we are describing algorithms and it would be nice to be able to copy and paste sections of the spec text into comments.

### PR DESCRIPTION
**Pull request by gkellogg**
[W3C Software and Document License](h…ttps://www.w3.org/Consortium/Legal/copyright-software).

Fixes #560.

### CODE REVIEW

**Comment by gkellogg** [comment]
Note, the spec license and test suite license are unchanged, but compatible.

The spec license is [here](https://github.com/json-ld/json-ld.org/blob/master/spec/LICENSE.md) and uses the [W3C DOCUMENT LICENSE](https://www.w3.org/Consortium/Legal/2015/doc-license) and [W3C COMMUNITY CONTRIBUTOR LICENSE AGREEMENT (CLA)](https://www.w3.org/community/about/agreements/cla/) licenses.

The test suite license is [here](https://github.com/json-ld/json-ld.org/blob/master/test-suite/LICENSE.md) and uses the [LICENSES FOR W3C TEST SUITES](https://www.w3.org/Consortium/Legal/2008/04-testsuite-copyright.html).

**Comment by davidlehn** [comment]
Does this need to include the whole text of that license?

The part about software libs with other licenses should stay, or somehow be added.  Bootstrap, various libs for the playground, and maybe other files are in the repo that have their own licenses.

**Comment by gkellogg** [comment]
Other W3C repos do it this way, so I think we're fine.

**Comment by gkellogg** [comment]
Having heard no response, I presume there are no objections to changing the site license.

**Pull request merged**
