### PR TITLE
Add TRLD to list of implementations

### PR DESCRIPTION
**Pull request by niklasl**

### CODE REVIEW

**Review by gkellogg — APPROVED** [review]

**Comment by gkellogg** [comment]
I think @davidlehn is going to need to chime in on the CloudFlare build issue.

**Comment by niklasl** [comment]
The addition is straightforward, so I assume the CloudFlare issue is something else? @davidlehn is there anything I can do to help?

**Comment by davidlehn** [comment]
Sorry for the delay.  This is a temporary glitch. CloudFlare got setup a bit too early to build PR previews with 11ty, but the 11ty support files (from the 11ty branch) haven't yet made it to main and those PRs.  I'm not sure how to temporarily shut that off easily, so we'll ignore it for now.

**Comment by niklasl** [comment]
@davidlehn Thank you (and no worries at all; it's great that you're looking into these site improvements)!

**Pull request merged**
