### PR TITLE
Add separate LICENSE.md files for specs and test-suite

### PR DESCRIPTION
**Pull request by gkellogg**
Update copyright footer on HTML files.

This is related to #417 and updates PR #456 to add LICENSE files to spec and test-suite directories. It also updates footers on all HTML files appropriately.

### CODE REVIEW

**Comment by gkellogg** [comment]
cc/ @dijonkitchen @BigBlueHat @msporny

**Comment by BigBlueHat** [comment]
I think leaving the "web site content" licensed under CC0 is fine. It's just the code that *needs* to be licensed under something else (i.e. the MIT as of #456).

The summary (afaik) looks like this (unless otherwise specified at the file level):
 - web site content - CC0
 - code - MIT
 - specs - W3C Document License & W3C CLA

That sound right?

**Comment by gkellogg** [comment]
Okay, I'll change the HTML copyright lines back, except for `spec` and `test-suite`.

**Comment by gkellogg** [comment]
Note, `test-suite` is covered by a separate [LICENSES FOR W3C TEST SUITES](https://www.w3.org/Consortium/Legal/2008/04-testsuite-copyright.html).

**Comment by BigBlueHat** [comment]
Looks good to me! 👍

**Pull request merged**
