### PR TITLE
Add CSP: upgrade-insecure-requests

### PR DESCRIPTION
**Pull request by BigBlueHat**
Fixes the Mixed Content mess...for real.

I have this in place on the [LevelGraph Playground](http://wileylabs.github.io/levelgraph-playground) and it works.

Cheers!
🎩

### CODE REVIEW

**Comment by gkellogg** [comment]
Looks like this is causing the playground to not load, I'm going to back it out.

**Comment by davidlehn** [comment]
http://caniuse.com/#search=upgrade-insecure-requests
This is not universally supported.  I just tested in Edge by adding "http://schema.org" to the `@context` in that above link.  It output a console "Access is deined." error.  So some other solution is still needed if the desire is to just blindly switch protocols.

I think sites should warn users if they are doing this.  Or maybe make it an option somehow.  In practice it's probably true that most sites serve the same data on https and http.  But that's not a requirement.  It's also very possible that a server for a http URL might not support https.  What happens in that case?

**Comment by gkellogg** [comment]
Site doesn't run HTTPS quite yet, once it does, we can re-apply this.

cc/ @davidlehn

**Comment by BigBlueHat** [comment]
Yeah. Sorry about this mess. It's not of my making of course. :wink: But obviously these attempts to fix the mess the browser are making by "aggressively deprecating HTTP" with these sort of sanctioned "hacks" aren't really going to solve for all the scenarios possible--especially in a playground such as this.

I'd also forgotten (apologies) that the json-ld.org site wasn't using HTTPS yet--whereas the [LevelGraph Playground](http://wileylabs.github.io/levelgraph-playground) is because of `*.github.io` URLs all being HTTPS now.

Anyhow. Apologies for yet-more-mess trying to solve for these scenarios.

I do hope some leadership in the Linked Data space surfaces that addresses this "rename all the things" situation...

Sorry again,
🎩

**Pull request merged**
